import '@mantine/core/styles.css';
import '@mantine/nprogress/styles.css';
import '@mantine/notifications/styles.css';

import "@restaview/styles/globals.css";


import Head from "next/head";

import localFont from 'next/font/local'

import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";

import { api } from "@restaview/utils/api";

import { MantineProvider, createTheme } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import { NavigationProgress } from '@mantine/nprogress';

import { FooterComponent, HeaderComponent } from '@restaview/components';

const theme = createTheme({});

const seedSans = localFont({
    src: [
        {
            path: './../../public/font/LINESeedSansTH_W_Th.woff2',
            weight: '100',
            style: 'normal'
        },
        {
            path: './../../public/font/LINESeedSansTH_W_Rg.woff2',
            weight: '400',
            style: 'normal'
        },
        {
            path: './../../public/font/LINESeedSansTH_W_Bd.woff2',
            weight: '700',
            style: 'normal'
        },
        {
            path: './../../public/font/LINESeedSansTH_W_XBd.woff2',
            weight: '800',
            style: 'normal'
        },
        {
            path: './../../public/font/LINESeedSansTH_W_He.woff2',
            weight: '900',
            style: 'normal'
        }
    ],
});

const MyApp: AppType<{ session: Session | null }> = ({
    Component,
    pageProps: { session, ...pageProps },
}) => {
    return (
        <SessionProvider session={session}>
            <Head>
                <title>Restaview - Reviews of restaurants that you must try.</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MantineProvider
                theme={theme}
                classNamesPrefix='restaview'
            >
                <Notifications position={'top-right'} zIndex={1000} />
                <NavigationProgress />
                <div className={seedSans.className}>
                    <HeaderComponent />
                    <Component {...pageProps} />
                    <FooterComponent />
                </div>
            </MantineProvider>
        </SessionProvider>
    );
};

export default api.withTRPC(MyApp);
